/** Asphalt & Signal v2 light palette; mirrors app/globals.css for native and map SDK consumers. */
export const designTokens = {
  "surface-ground": "#F6F6F4",
  "surface-card": "#FFFFFF",
  "text-primary": "#20252A",
  "text-secondary": "#545B63",
  "text-faint": "#545B63",
  "border-default": "#D3D5D1",
  "border-strong": "#20252A",
  "border-card": "#DCDEDA",
  "signal-fill": "#FFB800",
  "signal-on": "#20252A",
  "signal-text": "#8A5A00",
  "signal-tint": "#FFF3D1",
  "signal-tint-border": "#F1D48A",
  /** Frequent-place star: always drawn with a 1.5 ink outline (contrast vs. card is 1.73:1). */
  "star-fill": "#FFB800",
  "rain-high": "#1F4FA3",
  "rain-on-high": "#F4F6F9",
  "rain-low": "#DCE6F2",
  "rain-unknown": "#C3C8CF",
  "danger-text": "#B42318",
  "danger-fill": "#B42318",
  "danger-on": "#FFFFFF",
  "map-land": "#E2E5E1",
  "map-water": "#C6DAE6",
  "scrim": "rgb(32 37 42 / 40%)",
} as const;
